/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import client.Bidder;
import client.BidderCandidate;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author aka
 */
public class BidderForm extends javax.swing.JFrame {

    private Bidder bidder;
    private BidderCandidate bidderCandidate = new BidderCandidate();

    /**
     * Creates new form BidderForm
     */
    public BidderForm() {
        initComponents();
        bidderCandidate.sendAuctionListRequest();
        bidderCandidate.listenAuctionList(() -> {
            setAuctionList();
        });
        normalMode();
    }

    private void normalMode() {
        txt_nama.setEnabled(true);
        cmb_auction_list.setEnabled(true);
        btn_refresh.setEnabled(true);
        btn_join.setEnabled(true);

        txt_product_name.setVisible(false);
        txt_last_bid.setVisible(false);
        txt_last_bidder.setVisible(false);
        txt_price.setVisible(false);

        btn_make_bid.setVisible(false);

        lbl_last_bid.setVisible(false);
        lbl_last_bidder.setVisible(false);
    }

    private void auctionMode() {
        txt_nama.setEnabled(false);
        cmb_auction_list.setEnabled(false);
        btn_refresh.setEnabled(false);
        btn_join.setEnabled(false);

        txt_product_name.setVisible(true);
        txt_last_bid.setVisible(true);
        txt_last_bidder.setVisible(true);
        txt_price.setVisible(true);

        btn_make_bid.setVisible(true);

        lbl_last_bid.setVisible(true);
        lbl_last_bidder.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_auction_list = new javax.swing.JComboBox<>();
        btn_refresh = new javax.swing.JButton();
        btn_join = new javax.swing.JButton();
        txt_nama = new javax.swing.JTextField();
        panel_auction = new java.awt.Panel();
        txt_product_name = new javax.swing.JLabel();
        txt_last_bid = new javax.swing.JLabel();
        lbl_last_bid = new javax.swing.JLabel();
        btn_make_bid = new javax.swing.JButton();
        lbl_last_bidder = new javax.swing.JLabel();
        txt_last_bidder = new javax.swing.JLabel();
        txt_price = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmb_auction_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_refresh.setText("Refresh");
        btn_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refreshMouseClicked(evt);
            }
        });

        btn_join.setText("Join");
        btn_join.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_joinMouseClicked(evt);
            }
        });

        txt_product_name.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_product_name.setText("Product Name");

        txt_last_bid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_last_bid.setText("Rp. 5000");

        lbl_last_bid.setText("Last Bid");

        btn_make_bid.setText("Make Bid");
        btn_make_bid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_make_bidMouseClicked(evt);
            }
        });

        lbl_last_bidder.setText("Bidder");

        txt_last_bidder.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_last_bidder.setText("Name");

        txt_price.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        txt_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_priceKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_priceKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_auctionLayout = new javax.swing.GroupLayout(panel_auction);
        panel_auction.setLayout(panel_auctionLayout);
        panel_auctionLayout.setHorizontalGroup(
            panel_auctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_auctionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_auctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_auctionLayout.createSequentialGroup()
                        .addComponent(txt_product_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(86, 86, 86))
                    .addGroup(panel_auctionLayout.createSequentialGroup()
                        .addGroup(panel_auctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_auctionLayout.createSequentialGroup()
                                .addComponent(txt_last_bid, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_last_bidder))
                            .addGroup(panel_auctionLayout.createSequentialGroup()
                                .addGroup(panel_auctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_last_bid)
                                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(panel_auctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_last_bidder)
                                    .addComponent(btn_make_bid))))
                        .addGap(0, 24, Short.MAX_VALUE))))
        );
        panel_auctionLayout.setVerticalGroup(
            panel_auctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_auctionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_product_name)
                .addGap(18, 18, 18)
                .addGroup(panel_auctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_last_bid)
                    .addComponent(lbl_last_bidder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_auctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_last_bid)
                    .addComponent(txt_last_bidder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_auctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_make_bid)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nama)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmb_auction_list, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_refresh))
                                .addComponent(panel_auction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_join))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_auction_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_join)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_auction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refreshMouseClicked
        // TODO add your handling code here:
        bidderCandidate.sendAuctionListRequest();
    }//GEN-LAST:event_btn_refreshMouseClicked

    private void btn_joinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_joinMouseClicked
        // TODO add your handling code here:
        bidder = createBidder();
        if (bidder.joinAuction()) {
            txt_product_name.setText(bidder.getAuction().getProduct().getName());
            updateLastBid();

            bidder.listenBid(() -> {
                updateLastBid();
            }, () -> {
                bidderCandidate.sendAuctionListRequest();
                normalMode();
            });
            auctionMode();
        } else {
            JOptionPane.showMessageDialog(this, "Auction not started or already finished");
        }
    }//GEN-LAST:event_btn_joinMouseClicked

    private Bidder createBidder() {
        int index = cmb_auction_list.getSelectedIndex();
        return new Bidder(txt_nama.getText(), bidderCandidate.getAuctions().get(index));
    }

    private void btn_make_bidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_make_bidMouseClicked
        // TODO add your handling code here:
        int price = Integer.parseInt(unformatPrice(txt_price.getText()));
        bidder.makeBid(price);
    }//GEN-LAST:event_btn_make_bidMouseClicked

    private void txt_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceKeyTyped

    private void txt_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyReleased
        // TODO add your handling code here:
        limitText();
        int price = Integer.parseInt(unformatPrice(txt_price.getText()));
        txt_price.setText(formatPrice(price));
    }//GEN-LAST:event_txt_priceKeyReleased

    private void limitText() {
        if(txt_price.getText().length() >= 14)
            txt_price.setText(txt_price.getText().substring(0, 13));
    }
    
    private String unformatPrice(String price) {
        return price.replace(",", "");
    }
    
    private String formatPrice(int price) {
        DecimalFormat df = new DecimalFormat("###,###");
        return df.format(price);
    }
    
    private void setAuctionList() {
        System.out.println("set auction");
        cmb_auction_list.removeAllItems();
        bidderCandidate.getAuctions().forEach((auction) -> {
            cmb_auction_list.addItem(auction.getProduct().getName());
        });
    }

    private void updateLastBid() {
        txt_last_bidder.setText(bidder.getAuction().getLastBid().getUsername());
        txt_last_bid.setText("Rp. " + String.valueOf(formatPrice(bidder.getAuction().getLastBid().getPrice())));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BidderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BidderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_join;
    private javax.swing.JButton btn_make_bid;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JComboBox<String> cmb_auction_list;
    private javax.swing.JLabel lbl_last_bid;
    private javax.swing.JLabel lbl_last_bidder;
    private java.awt.Panel panel_auction;
    private javax.swing.JLabel txt_last_bid;
    private javax.swing.JLabel txt_last_bidder;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JFormattedTextField txt_price;
    private javax.swing.JLabel txt_product_name;
    // End of variables declaration//GEN-END:variables
}
